background                              #000000
foreground                              #E0E0E0
selection_foreground                     #E0E0E0
selection_background                     #555555

cursor                                   #E0E0E0

url_color                                #AAAAAA

visual_bell_color                        #FF5555

active_tab_foreground                     #E0E0E0
active_tab_background                     #666666
inactive_tab_foreground                   #AAAAAA
inactive_tab_background                   #111111

color0                                   #000000
color1                                   #555555
color2                                   #555555
color3                                   #666666
color4                                   #666666
color5                                   #777777
color6                                   #AAAAAA
color7                                   #CCCCCC
color8                                   #555555
color9                                   #666666
color10                                  #777777
color11                                  #888888
color12                                  #AAAAAA
color13                                  #999999
color14                                  #BBBBBB
color15                                  #E0E0E0


